Jpa buddy branch
Amplicode/amplicode-docs pull request #10
Opened 2023-05-10 07:45 UTC by irinaponomarevahaulmont

Please check the first drafts for #6 and #7.

2023-05-15 11:20 UTC, irinaponomarevahaulmont commented
Please check the draft. I have edited it for compliance.

2023-05-23 09:40 UTC, alexbudarov requested changes

2023-05-23 09:40 UTC, alexbudarov commented on content/modules/studio/pages/spring-data-jpa.adoc
> +
Add link to the detailed documentation:
https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#repositories

2023-05-23 09:40 UTC, alexbudarov commented on content/modules/studio/pages/spring-data-jpa.adoc
> +
In the end - I would like to see resulting code, how it looks like with entity graph.

And put links to the detailed documentation: 
https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#jpa.entity-graph
https://docs.jboss.org/hibernate/orm/current/userguide/html_single/Hibernate_User_Guide.html#fetching-strategies-dynamic-fetching-entity-graph

2023-05-23 09:40 UTC, alexbudarov commented on content/modules/studio/pages/spring-data-jpa.adoc
> +
Add link to doc.
"Read more about projections here:"
https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#projections

2023-05-23 09:40 UTC, alexbudarov commented on content/modules/studio/pages/spring-data-jpa.adoc
> +
Add link to doc: https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#auditing

"Read more about Spring Data Auditing here: "

2023-05-24 12:43 UTC, irinaponomarevahaulmont commented
Please check the amended version.

2023-05-25 08:28 UTC, alexbudarov commented on content/modules/studio/pages/spring-data-jpa.adoc
> +image::repository-creation-approach2.png[align=center]
no changes

2023-05-25 08:40 UTC, irinaponomarevahaulmont commented
I have cropped the screenshot. Remember doing this, but somehow it was lost. Please review.

2023-05-25 09:03 UTC, alexbudarov commented on content/modules/studio/pages/spring-data-jpa.adoc
> +
The example of projection (Order with just two attributes) is very lazy.
We have written: "In such cases, Spring Data JPA Projections come in handy, letting you return only required fields from queries."

How you can demonstrate only required fields, on an entity with just two attributes? It doesn't reflect the idea, there is no sense for Projection if you have entity with two fields.

You can take petclinic model if you need an example.
But even with this model, you have to choose a subset of attributes, not all of them. This is the idea of projection. Projection is not DTO.

Need to change examples and all screenshots for this sub-chapter, so we don't jump between two data models.

2023-05-25 09:15 UTC, alexbudarov commented on content/modules/studio/pages/tool-window.adoc
> +The toolbar contains the following icons:
I've realized now that again, all specific content of this toolbar, its description - belongs to JPA Entities chapter.
Here in the common chapter, we should just quickly describe what the toolbar is, and show a couple of example screenshots (e.g. for entity and for Liquibase script - they can be found in petclinic, *changelog.xml)

2023-05-25 12:29 UTC, irinaponomarevahaulmont commented
Please take another look.

2023-05-26 07:55 UTC, alexbudarov requested changes

2023-05-26 07:55 UTC, alexbudarov commented on content/modules/studio/pages/tool-window.adoc
When building antora, it displays an error

[11:07:51.040] ERROR (asciidoctor): target of image not found: editor-toolbar-liquibase.png
    file: /home/budarov/projects/amplicode/amplicode-docs/content/modules/studio/pages/tool-window.adoc
    source: /home/budarov/projects/amplicode/amplicode-docs (refname: jpa-buddy-branch <worktree>, start path: content)

2023-05-26 07:55 UTC, alexbudarov commented on content/modules/studio/images/references-output.png
Lazy screenshot, doesn't demonstrate the feature. Need to show at least out outgoing reference and one ingoing one.

2023-05-26 07:55 UTC, alexbudarov commented on content/modules/studio/pages/entity-designer.adoc
> +The icon named *_Spring Data Repositories_* shows the repository related to the currently opened Entity and offers an opportunity to create more repositories.
Here is a good place to put a link to the corresponding chapter (repositories) for devs who would like to know more about them. Can make it inline (e.g. clickable "create more repositories" text).

2023-05-26 07:55 UTC, alexbudarov commented on content/modules/studio/pages/entity-designer.adoc
> +Finally, DTOs and Spring Data Projections is the icon that gives us access to various actions that are necessary for working with Spring Data Projections and DTOs.
Here is a good place to put a link to the corresponding chapter (Projections) for devs who don't know that projections are and what is there purpose. Maybe they have found the icon in the Studio UI and came here to find out what projections are.

Also, it's better to create one DTO and one projection for this entity, so that the screenshot of the popup below will look more filled with content.

2023-05-26 07:55 UTC, alexbudarov commented on content/modules/studio/pages/spring-data-jpa.adoc
> +[[auditing-support]]
Please move Auditing Support section to JPA Entities chapter.
I've just realised that we structure the content a bit differently than JPAB docs do.
If we structure it from the point of Studio UI, than Audit palette items are available in the entity designer - and description should be located near to entities.

2023-05-29 05:59 UTC, irinaponomarevahaulmont commented
Please review again.

2023-05-29 07:58 UTC, merged