Vscode extension branch
Amplicode/amplicode-docs pull request #13
Opened 2023-05-17 11:25 UTC by irinaponomarevahaulmont

Please review the draft.

2023-05-22 12:31 UTC, alexbudarov requested changes

2023-05-22 12:31 UTC, alexbudarov commented on content/modules/vscode-extension/pages/index.adoc
> +is a free open-source IDE that supports frontend development and can be used as a free alternative to *_IntelliJ IDEA Ultimate Edition_*. In terms of Amplicode development, VS Code is a handy tool al
without having to pay license
-->
without depending on a commercial IDE
(softer wording)

2023-05-22 12:31 UTC, alexbudarov commented on content/modules/vscode-extension/pages/creating.adoc
> +Before creating a new frontend project in VS Code, you will need to run the corresponding backend application in IntelliJ IDEA using the debug icon (image:debug.png[align=center]).
We need backend not before creating the project.
We need it before running the project.
So better to move this sentence there.

2023-05-22 12:31 UTC, alexbudarov commented on content/modules/vscode-extension/pages/creating.adoc
> +For *_Backend Port_* keep the default value of 8080. For *_Generator Version_* use the current default value of 0.39.0. Click *_Generate_*.
Avoid mentioning exact value (0.39.0), if it's not required. "current recommended" version will increase soon.
User shouldn't worry about exact version number when he creates the project for the first time.

2023-05-22 12:31 UTC, alexbudarov commented on content/modules/vscode-extension/pages/working.adoc
> +In order to work with the project, we need to install npm.
It's not "install npm". It's just the name of the command.
See here: https://docs.npmjs.com/cli/v9/commands/npm-install

> npm install (in a package directory, no arguments):
> Install the dependencies to the local node_modules folder.

2023-05-22 12:31 UTC, alexbudarov commented on content/modules/vscode-extension/pages/working.adoc
Sub-sections are necessary here, because you describe several things to do.

2023-05-22 12:31 UTC, alexbudarov commented on content/modules/vscode-extension/pages/working.adoc
> +image::localhost.png[align=center]
re-shot screenshot, how it looks like in React Admin-based project.

2023-05-22 12:31 UTC, alexbudarov commented on content/modules/vscode-extension/pages/working.adoc
> +Open localhost:3000 in any browser. You will see the Welcome screen of the new frontend application.
Also add:
An alternative way to launch the frontend is to execute "npm run dev" in the terminal.

2023-05-23 07:43 UTC, irinaponomarevahaulmont commented
Please review the latest changes.

2023-05-24 09:01 UTC, alexbudarov commented on content/modules/vscode-extension/pages/creating.adoc
> +Open the folder (there will be a prompt), click *_Trust the Author_*. The project has been created. You can see the project tree on the left now.
> there will be a prompt

This is an important thing which can be easily missed by user, we should show it on the screenshot.

2023-05-24 09:54 UTC, irinaponomarevahaulmont commented
Please review, should be okay now.

2023-05-25 07:38 UTC, alexbudarov commented on content/modules/vscode-extension/pages/creating.adoc
> +Open the folder (there will be a prompt), click *_Trust the Author_*. The project has been created. You can see the project tree on the left now.
Not opening the folder manually.
User has more convenient ability to open just created project.

Show, how the prompt ("there will be a prompt") in the right-bottom corner looks like, after the project is created.

![image](https://github.com/Amplicode/amplicode-docs/assets/6158807/93296fe7-5e7c-43bb-ba6e-9231463578fb)

2023-05-25 08:32 UTC, irinaponomarevahaulmont commented
Please review the latest commit.

2023-05-26 06:52 UTC, merged