Creating Spring GraphQL controllers
Amplicode/amplicode-docs pull request #20
Opened 2023-06-14 09:37 UTC by irinaponomarevahaulmont

The first draft of the chapter has been committed. Please review.

2023-07-01 16:33 UTC, alexbudarov requested changes

2023-07-01 16:33 UTC, alexbudarov commented on content/modules/studio/pages/graphql-controller-designer.adoc
> +In the pop-up window that appears when we choose this option, we have to specify *_Type name_*, *_Field_* and *_Result type_*.
You have not described at all what these fields mean. Isn't this the purpose of documentation?

Type name - existing type of the GraphQL schema
Field - existing or new field of the selected type. Generated method will be automatically called to load this field.
Result type - field type (for new field)

2023-07-01 16:33 UTC, alexbudarov commented on content/modules/studio/pages/schema-first-development.adoc
> +The third way of creating a Spring for GraphQL Controller is to change the GraphQL schema first and then use a quick fix for code generation. This method is the most convenient for creating customize
If developer comes here by link, it is strange to read about "third" way.
One of ways, maybe?

2023-07-01 16:33 UTC, alexbudarov commented on content/modules/studio/pages/schema-first-development.adoc
> +eventEmptyWindows(date:Date!): [LocalDateTime]
add context around for clarity.
e.g.
```
type Query {
  ...
  eventEmptyWindows(date:Date!): [LocalDateTime]
}
```
It will help to understand.

2023-07-01 16:33 UTC, alexbudarov commented on content/modules/studio/pages/schema-first-development.adoc
> +This window contains all queries, mutations, types, enums, etc... The new elements will be marked with a green word *_new_*.
> contains all queries, mutations, types, enums, etc...

all - where? add:

... corresponding to existing controllers on the backend.

2023-07-01 16:33 UTC, alexbudarov commented on content/modules/studio/pages/schema-first-development.adoc
> +It is necessary to chck the checkbox corresponding to the new type.
chck

typo

2023-07-01 16:33 UTC, alexbudarov commented on content/modules/studio/pages/schema-first-development.adoc
> +options: [LocalDateTime]
align with spaces

2023-07-01 16:33 UTC, alexbudarov commented on content/modules/studio/pages/schema-first-development.adoc
> +Let us mark the new argument timeSpent as @SchemaMapping method. In this case we will need to specify the controller, to which this method will be placed.
@SchemaMapping method

should be styled as UI caption

2023-07-01 16:33 UTC, alexbudarov commented on content/modules/studio/pages/scalar-types.adoc
> +Scalar types are the types that resolve to a single scalar object and can't have sub-selections in the query.
Make a subsection - Scalar Types

Here we can clearly distinguish introduction and start of Scalar Types info

2023-07-01 16:33 UTC, alexbudarov commented on content/modules/studio/pages/scalar-types.adoc
> +https://datatracker.ietf.org/doc/html/rfc3339#section-5.6[RFC3339 date time formats]
This link like is in the outer space.
Should add some surrounding text and make the link more subtle, e.g. "Read here about RFC3339 date time formats"
where "here" is a link.
Thus it will look more nice.

2023-07-01 16:33 UTC, alexbudarov commented on content/modules/studio/pages/scalar-types.adoc
> +In the case when a generic class parametrized by another class is the result of an operation, then for each combination of the two types there will be a separate type generated
Missing dot in the end

2023-07-01 16:33 UTC, alexbudarov commented on content/modules/studio/pages/id-type.adoc
> +Technically, several ID fields can be declared for an object; in this case, the user has to select in the wizard, which field to use as the ID.
remove words starting from "in this case", it's outdated.
currently there are no any wizards that ask "which field to use as ID".

2023-07-01 16:33 UTC, alexbudarov commented on content/modules/studio/pages/id-type.adoc
> +    @QueryMapping(DefaultOwnerId)
> @QueryMapping(DefaultOwnerId)

This will not compile, operation name should be a string literal

2023-07-01 16:33 UTC, alexbudarov commented on content/modules/studio/pages/paging-sorting-filtering.adoc
> + . Parametres
Parametres --> Parameters

2023-07-01 16:33 UTC, alexbudarov commented on content/modules/studio/pages/paging-sorting-filtering.adoc
> + . The GraphQL schema must declare properties that can be used for sorting  (case Strict fields).
>   (case Strict fields)


remove this

2023-07-01 16:33 UTC, alexbudarov commented on content/modules/studio/pages/paging-sorting-filtering.adoc
> +public List<OwnerDTO> ownerListByNamesProperties(@Argument String firstName, @Argument String lastName) {
This line is too long, doesn't fit on my screen

2023-07-04 11:51 UTC, irinaponomarevahaulmont commented
Please review the latest version. I have deleted a few images + everything else as discussed.

2023-07-05 14:18 UTC, alexbudarov commented on content/modules/studio/pages/schema-first-development.adoc
> +The third way of creating a Spring for GraphQL Controller is to change the GraphQL schema first and then use a quick fix for code generation. This method is the most convenient for creating customize
> On of the ways of creating

Typo ?

2023-07-05 14:29 UTC, alexbudarov requested changes
1 typo left

2023-07-06 05:08 UTC, irinaponomarevahaulmont commented
Last typo corrected, please merge.

2023-07-06 07:21 UTC, merged