Working with DTO first draft
Amplicode/amplicode-docs pull request #21
Opened 2023-06-22 11:02 UTC by irinaponomarevahaulmont

Please review.

2023-06-26 16:11 UTC, alexbudarov requested changes

2023-06-26 16:11 UTC, alexbudarov commented on content/modules/studio/pages/working-with-dtos.adoc
> +Nowadays, the DTO pattern is widely used in software development. It is not only used with JPA entities, but also with regular POJO classes. With Studio, you are not restricted to using DTOs with jus
First two sentences look like a broad introduction. We don't need them in the middle of this chapter.

2023-06-26 16:11 UTC, alexbudarov commented on content/modules/studio/pages/working-with-dtos.adoc
> +Once we click OK, the new classes CharacterDto and Mapper will be generated. But now we need to add more methods to it - the methods to convert Play and Author entities to DTO and back.
styling as code

2023-06-26 16:11 UTC, alexbudarov commented on content/modules/studio/pages/working-with-dtos.adoc
> +DTOs are commonly used at the API controller level to define only the fields required by the client. This is why DTOs nearly copy the structure of their entities. There are popular frameworks to map
don't mention ModelMapper.
probably, should reformulate the sentence, like:
with Amplicode, you can use MapStruct library to map entities to DTOs and vice versa.

2023-06-26 16:11 UTC, alexbudarov commented on content/modules/studio/pages/working-with-dtos.adoc
> +It will suggest all the necessary changes in the names of methods, components and parameters including those located n the corresponding DTO class. We just need to decide which items in this list sho
located n

2023-06-26 16:11 UTC, alexbudarov commented on content/modules/studio/images/dto-navigation.png
Contents on the screenshot is too small.
I suggest to not show project tree, and resize a bit the IDE window to save some horizontal space.

2023-07-03 10:33 UTC, irinaponomarevahaulmont commented
I have applied the requested changes, please review.

2023-07-05 13:50 UTC, alexbudarov commented on content/modules/studio/pages/working-with-dtos.adoc
> +In order to do this, use the *_JPA Entity from POJO_* option available both in the Studio drop-down menu and in the main menu of your IDE.
You have not changed two similar captions below, headings of screenshots.

2023-07-05 13:51 UTC, alexbudarov commented on content/modules/studio/pages/working-with-dtos.adoc
> +In order to do this, use the *_JPA Entity from POJO_* option available both in the Studio drop-down menu and in the main menu of your IDE.
>  in the Context menu in the project tree

context menu - can be written in lower case, it's a term in user interfaces

2023-07-05 14:08 UTC, alexbudarov requested changes
few changes left

2023-07-05 14:08 UTC, alexbudarov commented on content/modules/studio/pages/working-with-dtos.adoc
> +https://mapstruct.org/[*_MapStruct_*] is a code generator that greatly simplifies the implementation of mappings. The *_Mapper class_* field appears in the *_New DTO_* window if your project contains
Change this link to a direct link to documentation:
https://mapstruct.org/documentation/1.4/reference/html/

And let's make this link a variable, to be defined outside of .adoc contents. So I can update it later easily when we will update platform's libraries.
As example, search for "main-site" in amplicode-docs, how it is defined in .yml files and how it is used in the content.

2023-07-06 09:30 UTC, irinaponomarevahaulmont commented
Requested changes addressed, please review.

2023-07-06 15:58 UTC, merged