Database branch
Amplicode/amplicode-docs pull request #25
Opened 2023-07-17 06:41 UTC by irinaponomarevahaulmont

The database-related chapters pushed for review. Pending: Database Driver, the decision on which screenshots use for Database Connections (Ultimate, Community or both). The rest is done.

2023-07-29 13:32 UTC, alexbudarov requested changes

2023-07-29 13:32 UTC, alexbudarov commented on content/modules/studio/pages/liquibase-support.adoc
> +image::liquibase-changelog-preview-2.png[align=center]
strange screenshot here.
it does not illustrate words that have been just said (about "prefilling changesets" and "exploring attributes of each element").

better: add a screenshot of any Palette item wizard, e.g. of Add -> Column item wizard.

2023-07-29 13:32 UTC, alexbudarov commented on content/modules/studio/pages/liquibase-support.adoc
> +image::sql-preview-window.png[align=center]
Screenshot contains private information (your IP address).

2023-07-29 13:32 UTC, alexbudarov commented on content/modules/studio/pages/liquibase-support.adoc
> +Sometimes software must provide support for a few DBMS types. In this case, Liquibase is the best choice, as it offers a cross-DB solution to declare DDL modifications. Studio supports this solution
is "few" a good word here? 
--> more than one / several
maybe.

2023-07-29 13:32 UTC, alexbudarov commented on content/modules/studio/pages/liquibase-support.adoc
> +Studio provides an ability to apply templates while generating changesets from the JPA Palette. This feature provides the ability to include various customizable elements in it:
JPA Palette --> Palette

2023-07-29 13:32 UTC, alexbudarov commented on content/modules/studio/pages/liquibase-support.adoc
> +  .  Create preconditions – each changeset can have specific preconditions. For example, `tableExists` and columnExists precondition tags will be added for the `addColumn` statement:
columnExists - not styled

2023-07-29 13:32 UTC, alexbudarov commented on content/modules/studio/pages/custom-type-mappings.adoc
> +You can change the saved mapping configuration at any time from *_Tools_* -> *_Amplicode_* -> *_Data Access_* -> *_Database Versioning_* -> *_Type Mappings_*.
again, this is a path inside of the settings
we should either say "... settings panel", or specify File -> Settings -> ...

2023-07-29 13:32 UTC, alexbudarov commented on content/modules/studio/pages/naming-strategy.adoc
> +RDBMSs have their own limitations. For example, table names for https://twitter.com/OracleDatabase[OracleDatabase] earlier than 12.1 version are limited to 30 bytes. To avoid problems with versioning
link to Twitter? weird

2023-07-29 13:32 UTC, alexbudarov commented on content/modules/studio/pages/naming-strategy.adoc
> +  *  primary key constraint name.
What can I define? One single constraint name for the whole project? Probably no. UI controls on the screenshot don't look one "name".

We should say a bit more about this setting, not just end up by repeating the field caption.

2023-07-29 13:32 UTC, alexbudarov commented on content/modules/studio/pages/liquibase-support.adoc
> +
It would be strange to start without making an introduction about the library.
Add a short introduction: what Liquibase is, 
and link the Liquibase site - https://docs.liquibase.com/concepts/introduction-to-liquibase.html

2023-07-31 06:36 UTC, irinaponomarevahaulmont commented on content/modules/studio/pages/database-connections.adoc
> +Since *_IntelliJ IDEA Community Edition_* doesn't allow configuring database drives, Studio offers you an alternative. Open *_Tools_* -> *_Amplicode_* -> *_Data Access_* -> *_Database Drivers_* windo
On my Mac it is not under File at all, but under IntelliJ IDEA.

2023-08-01 06:40 UTC, irinaponomarevahaulmont commented
Please review the requested changes.

2023-08-02 16:15 UTC, alexbudarov requested changes

2023-08-02 16:15 UTC, alexbudarov commented on content/modules/studio/pages/naming-strategy.adoc
> +The constraint can be named or unnamed. If we check the *_Named_* radiobutton, the default prefix for all primary key constraints will be *_PK_* (short for *_primary key_*). We can change this settin
Make some transition between "primary key constraint name." and "The constraint ".
It is not obvious now that paragraph below belongs to the list item.

You can make paragraphs below the part of the list.
Or add " - described below."

2023-08-02 16:15 UTC, alexbudarov commented on content/modules/studio/images/database-versioning/add-column-wizard.png
Enormous amount of empty space on the screenshot.

2023-08-02 16:15 UTC, alexbudarov commented on content/modules/studio/images/database-versioning/create-persistence-unit.png
Please update PetClinic project and recreate the screenshot.
I asked guys to rename root package from "io.jmix2mvp" to "com.amplicode", to avoid unnecessary associations.

2023-08-02 16:15 UTC, alexbudarov commented on content/modules/studio/pages/liquibase-support.adoc
> +*_Liquibase_* is a database-independent library that helps us with tracking, managing and applying database schema changes. All changes to the database are stored in text files (changelogs). Every ti
> soliution

another one

2023-08-02 16:15 UTC, alexbudarov commented on content/modules/studio/images/database-versioning/type-mappings.png
This screenshot is lazy (because settings aren't filled with any value).
Let's specify one row in the table to illustrate what was said in the paragraph above:

- Selected database - mssql
- Attribute/Converter/... - java.lang.String
- Target Type - nvarchar
- Type parameters - Length

2023-08-04 10:21 UTC, irinaponomarevahaulmont commented on content/modules/studio/images/database-versioning/add-column-wizard.png
I have trimmed it as much as possible without destroying the gradient.

2023-08-07 06:36 UTC, irinaponomarevahaulmont commented
Please review the second round of requested changes applied.

2023-08-07 07:55 UTC, alexbudarov requested changes

2023-08-07 07:55 UTC, alexbudarov commented on content/modules/studio/pages/liquibase-support.adoc
> +image::database-versioning/autoincrement.png[align=center]
This screenshot does not illustrate "providing code completion based on the JPA data model".
createIndex / createProcedure / ... completions are available out-of-the-box in IDEA, without our plugin.

You should create screenshot when developer has auto-completion list for tableName, columnName or indexName attributes, with the list of tables of columns (determined by the entities in the current project).

2023-08-09 19:56 UTC, merged