Graphql controller branch
Amplicode/amplicode-docs pull request #29
Opened 2023-07-26 07:25 UTC by irinaponomarevahaulmont

I have added the page dedicated to synchronization of the GraphQL schema. Please review.

2023-08-04 15:54 UTC, alexbudarov requested changes

2023-08-04 15:54 UTC, alexbudarov commented on content/modules/studio/pages/graphql-schema-generation.adoc
Menu structure is a bit broken.
Studio Schema Synchronization Action and Changes Preview Dialog
is not a child of the GraphQL Schema Synchronization (it if was supposed to be so).

2023-08-04 15:54 UTC, alexbudarov commented on content/modules/studio/pages/studio-schema-synchronization-action.adoc
> += Studio Schema Synchronization Action and Changes Preview Dialog
Let's shorten the title a bit.
"Schema Synchronization and Changes Preview"

2023-08-04 15:54 UTC, alexbudarov commented on content/modules/studio/pages/studio-schema-synchronization-action.adoc
> +Once we have applied certain alterations to our Amplicode-based project, we need to synchronize the GraphQL schema in order to ensure that it reflects the actual state of queries, mutations, data typ
We will need a bit longer introduction (why and when invoke this action?)
I will describe it during a Monday call.

2023-08-04 15:54 UTC, alexbudarov commented on content/modules/studio/pages/studio-schema-synchronization-action.adoc
> +The second drop-down box sets the mode of treating whitespaces and empty lines while comparing the two versions of the file. It contains the following options:
Below are described many non-important things (we will remove them).

But main actions (Ignore and Revert on the left above the changes tree) are not described.
I will describe them on Monday call.

2023-08-04 15:54 UTC, alexbudarov commented on content/modules/studio/pages/studio-schema-synchronization-action.adoc
> +
Mention that synchronization is also automatically launched as a prelinimary step before some frontend-related actions (e.g. when "Frontend Component" creation wizard is invoked). If developer doesn't want to apply changes, he/she can press Cancel to skip them.

2023-08-04 15:54 UTC, alexbudarov commented on content/modules/studio/pages/studio-schema-synchronization-action.adoc
> +
Mention, demonstrate various changes (new element green, modified element blue, removed element red).
Mention Ignored section.

2023-08-09 06:22 UTC, irinaponomarevahaulmont commented
Please review the rewritten version.

2023-08-09 19:47 UTC, alexbudarov requested changes

2023-08-09 19:47 UTC, alexbudarov commented on content/modules/studio/pages/studio-schema-synchronization-action.adoc
> +In the left upper corner you can see two important icons: *_Ignore_* and *_Revert Ignore_*.
They are not "icons". They are buttons or "icon buttons".
See in IntelliJ UI guidelines: https://jetbrains.github.io/ui/controls/icon_button/

Change here and below.

2023-08-09 19:47 UTC, alexbudarov commented on content/modules/studio/pages/studio-schema-synchronization-action.adoc
> +One of the methods of creating a GraphQL API, which is supported by Studio, is backend-first development. It means that first of all the developer defines controllers at the backend side. After that
Is "first of all" correctly used here?
Because these coding sessions: change backend - synchronize schema - change backend - synchronize again - ...
They can repeat many times.

2023-08-09 19:47 UTC, alexbudarov commented on content/modules/studio/pages/studio-schema-synchronization-action.adoc
> +The Spring for GraphQL library presumes that the developer, in the course of creating an application, writes up the schema file and declares the backend elements according to the schema: annotated co
> perfect match

I wouldn't say the match needs to be perfect.
Because there can be some little inconsistencies between schema and backend, but I don't want to explain them in the documentation.

2023-08-09 19:47 UTC, alexbudarov commented on content/modules/studio/pages/studio-schema-synchronization-action.adoc
> +The Preview Window contains an additional toolbar, which allows you to customize the look of the window.
> which allows you to customize the look of the window

Ignore and Revert Ignore are not for customizing the look of the window...

2023-08-09 19:47 UTC, alexbudarov commented on content/modules/studio/pages/studio-schema-synchronization-action.adoc
> +== Additional Preview Window Features
I would like to put Ignore and Revert Ignore into additional sub-section.
Because they are important, shouldn't be missed by user.  They are not "additional".
Name can be e.g. "Ignoring proposed schema changes".

2023-08-29 06:07 UTC, irinaponomarevahaulmont commented
Please review the latest changes.

2023-09-03 13:18 UTC, merged