Reverse engineering branch
Amplicode/amplicode-docs pull request #30
Opened 2023-07-31 04:30 UTC by irinaponomarevahaulmont

Please review. Awaiting a fix of the Hibernate Types library renaming issue. Images in a subfolder, for the .adoc files we would have to change the antora script to do the same, so I'm postponing it. The rest is ready for review.

2023-09-08 13:58 UTC, alexbudarov requested changes

2023-09-08 13:58 UTC, alexbudarov commented on content/modules/studio/pages/reverse-engineering.adoc
> +. Most DB views are immutable. So, Studio adds @Immutable annotation to the entity and generates getters only. This helps to improve application performance
> @Immutable

style as code

2023-09-08 13:58 UTC, alexbudarov commented on content/modules/studio/pages/reverse-engineering.adoc
> +image::reverse-engineering/ri-select-primary-key-window.png[align=center]
giant screenshot

2023-09-08 13:58 UTC, alexbudarov commented on content/modules/studio/pages/reverse-engineering.adoc
> +After that, the Reverse Engineering Columns wizard will appear:
The caption of this dialog is different now. You can see on the screenshot.

2023-09-08 13:58 UTC, alexbudarov commented on content/modules/studio/pages/reverse-engineering.adoc
> +Since `@Id` should not be a persistence entity, Studio will generate:
This paragraph isn't well understandable without context ('id', 'users'). And isn't necessary IMHO.
So let's delete it.

2023-09-08 13:58 UTC, alexbudarov commented on content/modules/studio/pages/reverse-engineering.adoc
> +If a table has a column that refers to the primary key of another table, it is most likely a `@ManyToOne` association. But you are also able to change cardinality to `@OneToOne` if required. So, depe
Unnecessary colon in the end.

2023-09-08 13:58 UTC, alexbudarov commented on content/modules/studio/pages/reverse-engineering.adoc
> +For the Ultimate edition of the IDE a different mechanism has been implemented. An internal mechanism built into IntelliJ IDEA Untimate edition takes responsibility for caching the state of the datab
typo: Untimate

2023-09-08 13:58 UTC, alexbudarov commented on content/modules/studio/pages/reverse-engineering-settings.adoc
> +* Add the `@JavaType` annotation to the relevant attribute and specify the required implementation
The following scenario does not demonstrate reverse engineering.
It demonstrates generation of SQL scripts by data model.

We need to show (it's in the end of the Buddy's video):
1) Register smallint -> Boolean in the settings
2) Create table in the database that has a smallint column
3) Reverse-engineer this table and demonstrate that Studio offers Boolean as column type.
4) Show, which entity code was generated by Studio (Boolean field marked with BooleanJavaType).

2023-09-14 10:10 UTC, irinaponomarevahaulmont commented on content/modules/studio/pages/reverse-engineering-settings.adoc
> +* Add the `@JavaType` annotation to the relevant attribute and specify the required implementation
Ok, I have addded it to the end of the document, without deleting the other one, since it seems important too.

2023-09-14 10:25 UTC, irinaponomarevahaulmont commented
Please review the corrections.

2023-09-17 10:35 UTC, alexbudarov commented on content/modules/studio/pages/reverse-engineering-settings.adoc
> +* Add the `@JavaType` annotation to the relevant attribute and specify the required implementation
First scenario is a different feature. It isn't "reverse" engineering. It is direct engineering.
You can move it to the Database Versioning -> Custom Type Mappings section.

2023-09-17 10:37 UTC, alexbudarov requested changes

2023-09-17 10:37 UTC, alexbudarov commented on content/modules/studio/pages/reverse-engineering-settings.adoc
> +* Reverse-engineer the new field into the entity. It should be suggested as `BooleanJavaType` -> `Boolean`.
> Reverse-engineer the new field into the entity.

Too short. What actions should I invoke?

2023-09-19 15:44 UTC, merged