The first version of the Marketplace chapter #28
Amplicode/amplicode-docs pull request #31
Opened 2023-08-02 06:59 UTC by irinaponomarevahaulmont

Please review.

2023-08-09 19:13 UTC, alexbudarov requested changes

2023-08-09 19:13 UTC, alexbudarov commented on content/modules/studio/pages/marketplace.adoc
> +Studio provides useful UI to manage add-ons in your application. The Add-ons dialog is accessible from the Editor Toolbar.
> from the Editor Toolbar

It's not "Editor" Toolbar. Editor Toolbar is a bar on top of the source code editor.

2023-08-09 19:13 UTC, alexbudarov commented on content/modules/studio/pages/marketplace.adoc
> +image::marketplace/installed-add-on-message.png[align=center]
On the screenshot, an **un**installed notification is displayed.

2023-08-09 19:13 UTC, alexbudarov commented on content/modules/studio/pages/marketplace.adoc
> +To uninstall an add-on, you need to go to the `Installed`
Wrong styling for "Installed" and "Uninstall"
(these are UI captions)

2023-08-28 10:42 UTC, irinaponomarevahaulmont commented
Corrections made, please review.

2023-08-28 16:18 UTC, merged