Email Templates first version #26
Amplicode/amplicode-docs pull request #32
Opened 2023-08-28 08:17 UTC by irinaponomarevahaulmont

The first version of the Email Templates chapter without code snippets. Please review.

2023-08-28 09:02 UTC, m-orlova commented on content/modules/email-template/pages/index.adoc
> +The add-on enables creating and configuring outbound email templates containing a constant body and variable parameters. A template is created in the visual HTML designer or by using reports. The add
"or by using reports" - not needed, we don't have this feature.

2023-08-28 09:06 UTC, m-orlova commented on content/modules/email-template/pages/index.adoc
> +   * Visual HTML templates builder based on GrapesJs JavaScript library
1. Add a link (grapesjs.com) to the "GrapesJs" word as it is done in Jmix documentation.
2. Need to add a dot to the end of the sentence.

2023-08-28 09:08 UTC, m-orlova commented on content/modules/email-template/pages/index.adoc
> +   * Downloading/uploading HTML code of a template
Need to add a dot to the end of the sentence.

2023-08-28 09:24 UTC, m-orlova commented on content/modules/email-template/pages/index.adoc
> +For automatic installation through Amplicode Marketplace, follow instructions in the Marketplace section. Studio will generate a preview window for the necessary changes to the GraphQL schema file re
1. For automatic installation through Amplicode Marketplace, follow instructions **in the Marketplace section.**- link   to the corresponding section is missed?
2. "**Studio will generate a preview window** for the necessary changes to the GraphQL schema file **related to Email Templates**. Once you accept these changes by clicking *_OK_*, they will be applied to the schema file." 
     - Studio shows the "GraphQL Schema Changes preview" window but does not generate a preview window.
     - Under "related to Email Templates" means "related to the Email Templates add-on"?

2023-08-28 09:43 UTC, m-orlova commented on content/modules/email-template/pages/getting-started.adoc
> +Create repositories, Spring for GraphQL controllers and simple CRUD screens for the `Applicant` and `Grant` entities.
For the `Applicant` and `Grant` entities:
1. Create the Spring Data repositories. _(Also, add a link to the doc for repository creation if it exists.)_
2. Create the Spring GraphQL controllers for CRUD operations. _(Also, add a link to the doc for the Spring GraphQL controllers creation if it exists.)_
3. Regenerate GraphQL schema.
4. Create simple CRUD screens in the React UI module.

**Note:** Not forget to update the database structure.

2023-08-28 09:55 UTC, m-orlova commented on content/modules/email-template/pages/getting-started.adoc
> +Start the application and open the *_Email templates_* screen. Click the *_Create_* button.
"Start the application and open the *_Email templates_* screen." Maybe we will add a bit more details like "Start the application (backend and frontend) and open the launched application in browser. Open the *_Email templates_* screen from the menu.

2023-08-28 09:58 UTC, m-orlova commented on content/modules/email-template/pages/getting-started.adoc
> +Switch to the *_Email Sending_* tab and modify the Subject field:
"Switch to the *_Email Sending_* tab and modify **the Subject field**:" - it seems not correct, more suitable: "and modify the following fields:"

2023-08-28 09:59 UTC, m-orlova commented on content/modules/email-template/pages/getting-started.adoc
> +  *  *_From_*: `email@email.com` (replace with the actual email address corresponding to the SMTP server you are using for tests).
Let's change `email@email.com` to `info@company.com`.

2023-08-28 10:05 UTC, m-orlova commented on content/modules/email-template/pages/getting-started.adoc
> +In the template, we can use the template’s parameters. Those parameters will be created automatically. Type `Hi, ${applicant.firstName} ${applicant.lastName}!` with parameters mask in the *_Text_* el
"Those parameters will be created automatically." - not needed, we don't have automatic creation for the parameters as in Jmix. We can add parameters manually on the Input parameters tab.

2023-08-28 10:08 UTC, m-orlova commented on content/modules/email-template/pages/getting-started.adoc
> +* `First Name`, alias `firstName`, type `String`
* **Name:** `First name`, **Alias:** `firstName`, **Type**: `String`, **Required**: yes.
* **Name:** `Last name`, **Alias:** `lastName`, **Type**: `String`, **Required**: yes.

2023-08-28 11:21 UTC, m-orlova commented on content/modules/email-template/pages/getting-started.adoc
> +In the template, we can use the template’s parameters. Those parameters will be created automatically. Type `Hi, ${applicant.firstName} ${applicant.lastName}!` with parameters mask in the *_Text_* el
Replace ${applicant.firstName} with ${firstName} and ${applicant.lastName} with ${lastName}.

2023-08-28 11:24 UTC, m-orlova commented on content/modules/email-template/pages/getting-started.adoc
> +Now we need to add three more parameters, which are:
"Now we need to add three more parameters, which are:" -> Need to specify that parameters are used in the text above, so that's why we need to add them to the template. For example: "Now we need to add three more parameters used in the text above, which are:"

2023-08-28 11:26 UTC, m-orlova commented on content/modules/email-template/pages/getting-started.adoc
> +
* **Name**: `Amount`, **Alias**: `amount`, **Type**: `Decimal`, **Required**: yes.
* **Name**: `Date Of Approval`, **Alias**: `dateOfApproval`, **Type**: `Date`, **Required**: yes.
* **Name**: `Purpose`, **Alias**: `purpose`, **Type**: `String`, **Required**: yes.

2023-08-28 11:31 UTC, m-orlova commented on content/modules/email-template/pages/getting-started.adoc
> +Open the *_Email templates_* browser, select the created template and click the *_Send_* button.
Why? It is not needed if we don't send email from the UI in this guide. Please remove this sentence.

2023-08-28 11:36 UTC, m-orlova commented on content/modules/email-template/pages/getting-started.adoc
> +image::email-template-ready.png[align=center]
Incorrect screenshot for the result template, input parameters are not the same as in the descriptions above. Formatting of date and number is wrong.

2023-08-28 12:08 UTC, m-orlova commented on content/modules/email-template/pages/getting-started.adoc
> +== Adding Source Code
The "Adding Source Code" title is not clear, it is difficult to understand what this section is about. Possible titles:  Sending Email By Template, Adding Automatic Email Sending or maybe there is another idea for title.

2023-08-28 12:55 UTC, m-orlova commented on content/modules/email-template/pages/getting-started.adoc
> +    public void sendConfirmationEmail (Grant grant) {
Remove space before "(Grant grant)", IntelliJ IDEA does not add spaces in this case.

2023-08-28 12:55 UTC, m-orlova commented on content/modules/email-template/pages/getting-started.adoc
> +    public void sendConfirmationEmail (Grant grant) {
Remove space before "(Grant grant)", IntelliJ IDEA does not add spaces in this case.

2023-08-28 12:56 UTC, m-orlova commented on content/modules/email-template/pages/getting-started.adoc
> +                .addParam("firstName", firstName)
Use "applicant.getFirstName()" instead of "firstName". Example:  `.addParam("firstName", applicant.getFirstName())`.

2023-08-28 12:59 UTC, m-orlova commented on content/modules/email-template/pages/getting-started.adoc
> +                .addParam("amount", amount)
Use `grant.getAmount()` instead of `amount`. Example: `.addParam("amount", grant.getAmount())`.

2023-08-28 13:00 UTC, m-orlova commented on content/modules/email-template/pages/getting-started.adoc
> +                .addParam("purpose", purpose)
Use `grant.getPurpose()` instead of `purpose`. Example: `.addParam("purpose", grant.getPurpose())`.

2023-08-28 13:01 UTC, m-orlova commented on content/modules/email-template/pages/getting-started.adoc
> +    public void sendConfirmationEmail (Grant grant) {
Remove space before "(Grant grant)", IntelliJ IDEA does not add spaces in this case.

2023-08-28 13:04 UTC, m-orlova commented on content/modules/email-template/pages/getting-started.adoc
> +
Remove lines [314-318] and use getters to add param value below:
```
 emailTemplateSender.byEmailTemplateCode(GRANT_CONFIRMATION_TEMPLATE_CODE)
                    .withTo(applicant.getEmail())
                    .addParam("firstName", applicant.getFirstName())
                    .addParam("lastName",  applicant.getLastName())
                    .addParam("amount", grant.getAmount())
                    .addParam("dateOfApproval", grant.getDateOfApproval())
                    .addParam("purpose", grant.getPurpose())
                    .sendEmail();
```

2023-08-28 13:10 UTC, m-orlova commented on content/modules/email-template/pages/getting-started.adoc
> +    private final EmailTemplates emailTemplates;
Let's add a number with the description like "`EmailTemplates` provides CRUD operations for email templates."

2023-08-28 13:11 UTC, m-orlova commented on content/modules/email-template/pages/getting-started.adoc
> +    private final EmailTemplateSender emailTemplateSender;
Let's add a number with the description like "`EmailTemplateSender` provides methods for sending email by template."

2023-08-28 13:14 UTC, m-orlova commented on content/modules/email-template/pages/getting-started.adoc
> +        }  <2>
Not necessary description under number, that can be omitted, because it is not related directly to the add-on functionality.

2023-08-28 13:16 UTC, m-orlova commented on content/modules/email-template/pages/getting-started.adoc
> +                    .withTo(applicant.getEmail())
Let's add a number with the description like "Sets the recipient of an email"

2023-08-28 13:20 UTC, m-orlova commented on content/modules/email-template/pages/getting-started.adoc
> +                    .addParam("purpose", purpose)
For rows like `.addParam` let's add numbers and common description like:
"4-9 - Sets values for the template parameters with aliases: `firstName`, `lastName`, `amount`,  `dateOfApproval` and `purpose`."

2023-08-28 13:21 UTC, m-orlova commented on content/modules/email-template/pages/getting-started.adoc
> +                    .sendEmail(); <4>
Update description under number for this row: "Forms the email based on the selected template, sends it and stores in the email history."

2023-08-28 13:23 UTC, m-orlova commented on content/modules/email-template/pages/getting-started.adoc
> +            log.error ("Failed to send confirmation email"); <5>
Update code to `log.error("Failed to send confirmation email", e);`

2023-08-28 13:27 UTC, m-orlova commented on content/modules/email-template/pages/getting-started.adoc
> +image::palette-and-canvas.png[align=center]
Titles of editor tabs are cut.

2023-08-28 13:28 UTC, m-orlova commented on content/modules/email-template/pages/getting-started.adoc
> +image::text-element.png[align=center]
Replace ${applicant.firstName} with ${firstName} and ${applicant.lastName} with ${lastName} on screenshot.

2023-08-28 14:11 UTC, m-orlova commented on content/modules/email-template/pages/getting-started.adoc
> +image::preview-button.png[align=center]
Not sure about Preview description, because it is not the same Preview as in Jmix documentation.

2023-08-28 14:18 UTC, m-orlova commented on content/modules/email-template/pages/getting-started.adoc
> +First of all, find the `update()` method for the `Grant` entity (it should be in the `GrantController` class) and add the following code to the method before the return statement:
It is hard to understand the result code of the `update` method of GrantController.

Maybe we change the order for adding the code (need to discuss):
1. Firstly we create a service (`GrantService`) with method to send email by template using specified Grant entity.
2. Show the result code of the `update` method in GrantController and add a number with description to the row where email will be sent.

2023-08-28 14:36 UTC, m-orlova commented on content/modules/email-template/partials/nav.adoc
>  ** xref:email-template:getting-started.adoc[]
"Getting started" should be first. The order of articles:
1. Getting started
2. Configuration
3. Usage
4. Email Templates API

2023-08-28 15:03 UTC, m-orlova commented on content/modules/email-template/pages/usage.adoc
> +  *  *_Code_* -- unique template name; it can be used to find the correct template using API
Dot is missed at the end of sentence?

2023-08-28 15:03 UTC, m-orlova commented on content/modules/email-template/pages/usage.adoc
> +  *  *_Description_* -- an optional description of the template
Dot is missed at the end of sentence?

2023-08-28 15:03 UTC, m-orlova commented on content/modules/email-template/pages/usage.adoc
> +  *  *_Subject_* -- default email subject
Dot is missed at the end of sentence?

2023-08-28 15:03 UTC, m-orlova commented on content/modules/email-template/pages/usage.adoc
> +  *  *_From_* -- default sender’s address
Dot is missed at the end of sentence?

2023-08-28 15:04 UTC, m-orlova commented on content/modules/email-template/pages/usage.adoc
> +  *  *_To_* -- default recipient’s address
Dot is missed at the end of sentence?

2023-08-28 15:04 UTC, m-orlova commented on content/modules/email-template/pages/usage.adoc
> +  *  *_Cc_* -- additional recipient’s address
Dot is missed at the end of sentence?

2023-08-28 15:05 UTC, m-orlova commented on content/modules/email-template/pages/usage.adoc
> +Most of the tools used to create a template are located on the *_General_* tab. Here, you can fill in the *_Name_*, *_Code_* and *_Description_* fields, add elements to the canvas with the help of th
"Most of the properties" instead of "Most of the tools"

2023-08-28 15:08 UTC, m-orlova commented on content/modules/email-template/pages/usage.adoc
> +Parameters and value formats can be created and configured in the *_Input Parameters_* tab.
We have no configuration for value formats, the input parameters only.

2023-08-29 10:36 UTC, m-orlova commented on content/modules/email-template/pages/usage.adoc
> +*_Add Filter_* allows you to create filters by name and by code. Once you have created a filter, only thos templates that match the filter will be displayed. For example, if we select filter by name
"only **thos** templates" - a typo?

2023-08-29 12:59 UTC, m-orlova reviewed
Review of the "Usage" article

2023-08-29 12:59 UTC, m-orlova commented on content/modules/email-template/pages/usage.adoc
> + * Template creator/editor (pictured below)
Email Template Create/Edit component

2023-08-29 12:59 UTC, m-orlova commented on content/modules/email-template/pages/usage.adoc
> + * Email information/email sending screen.
Email sending component

2023-08-29 12:59 UTC, m-orlova commented on content/modules/email-template/pages/usage.adoc
> +Below we will describe every screen and its main functionality.
Replace "screen" with "component"

2023-08-29 12:59 UTC, m-orlova commented on content/modules/email-template/pages/usage.adoc
> +This is the first screen you see when you click on *_Email templates_* in the main menu of your application.
Replace "screen" with "component"

2023-08-29 12:59 UTC, m-orlova commented on content/modules/email-template/pages/usage.adoc
> +This screen contains template cards for all existing templates. Clicking on a card allows you to view the selected template in the read-only mode.
1. Replace "screen" with "component".
2. template cards -> email template cards.
3. selected template -> selected email template.

2023-08-29 12:59 UTC, m-orlova commented on content/modules/email-template/pages/usage.adoc
> +The *_Send email_* button (image:the-send-button.png[]) takes you to the xref:#email-sending[Email Sending] screen.
Replace "screen" with "component"

2023-08-29 12:59 UTC, m-orlova commented on content/modules/email-template/pages/usage.adoc
> +=== Template Creator/Editor
Email Template Create/Edit component

2023-08-29 12:59 UTC, m-orlova commented on content/modules/email-template/pages/usage.adoc
> +To open this screen, click the *_Create_* button from the *_Template Listing_* screen. The editor is based on a https://grapesjs.com/[GrapesJs JavaScript library] with an extensive set of HTML elemen
1. Replace "screen" with "component". 
2. Need to specify what editor is based on GrapesJs. For example, "visual editor for email template content".

2023-08-29 12:59 UTC, m-orlova commented on content/modules/email-template/pages/usage.adoc
> +The button panel contains action buttons related to the most important functionality of the template editor. It is located above the Palette.
Not sure if we should use "template" instead of "email template".

2023-08-29 12:59 UTC, m-orlova commented on content/modules/email-template/pages/usage.adoc
> +Each template card on the *_Template Listing_* screen contains a *_Send email_* button.
the *_Template Listing_* screen -> the Email Templates List component

2023-08-29 12:59 UTC, m-orlova commented on content/modules/email-template/pages/usage.adoc
> +Clicking it takes you to the *_Email info_* screen that displays known information about the selected email template and allows you to send an email directly from the Email Templates UI.
the *_Email info_* screen -> the *_Email sending_* component

2023-08-29 12:59 UTC, m-orlova commented on content/modules/email-template/pages/usage.adoc
> +Notice that the field values that had been filled in through the *_Email Sending_* tab will be displayed here automatically. The rest of the mandatory  fields will have to be filled manually in order
Replace "screen" with "component"

2023-08-29 12:59 UTC, m-orlova commented on content/modules/email-template/pages/usage.adoc
> +The *_View Template_* button will allow you to see the template in the read-only mode.
1. Screenshot for this screen?
2.  the template -> the email template

2023-08-29 12:59 UTC, m-orlova commented on content/modules/email-template/pages/usage.adoc
> +
Need to discuss:
1. Move usage for email template to subarticle.
2. Add subarticle about email history usage.
3. Add subarticle about email scheduler usage.

So we should get the following structure of articles:

Usage:
  - Email templates
  - Email history
  - Email scheduler

2023-08-29 12:59 UTC, m-orlova commented on content/modules/email-template/pages/usage.adoc
> +=== Template Listing
Email Templates List component

2023-08-29 12:59 UTC, m-orlova commented on content/modules/email-template/pages/usage.adoc
> +Clicking the *_Copy_* button (image:copy-button.png[]) creates an exact copy of the template.
template -> email template

2023-08-29 12:59 UTC, m-orlova commented on content/modules/email-template/pages/usage.adoc
> +Finally, the *_Delete_* (image:delete-button.png[]) button allows you to delete a template.
a template -> an email template

2023-08-29 12:59 UTC, m-orlova commented on content/modules/email-template/pages/usage.adoc
> +There are also buttons related to the whole screen rather than a separate template card. These are:
1. screen -> component
2. template -> email template

2023-08-29 12:59 UTC, m-orlova commented on content/modules/email-template/pages/usage.adoc
> +*_Add Filter_* allows you to create filters by name and by code. Once you have created a filter, only thos templates that match the filter will be displayed. For example, if we select filter by name
1. "*_Add Filter_* allows you to create filters by name and by code." - add "ignoring the case" because the case is ignored during filtering.
2. on the screen -> on the component.

2023-08-29 12:59 UTC, m-orlova commented on content/modules/email-template/pages/usage.adoc
> +*_Create_* will take us to the screen where we can create a new template.
screen -> component

2023-08-29 12:59 UTC, m-orlova commented on content/modules/email-template/pages/usage.adoc
> +The editor contains the following tabs: *_General_*, *_Input Parameters_*, *_Email Sending_* and *_Attachments_* tabs.
The editor -> The Email Template Create/Edit component

2023-08-29 12:59 UTC, m-orlova commented on content/modules/email-template/pages/usage.adoc
> +To create a template, you should set the following template parameters:
parameters -> attributes, to differ email template attribute and template input parameter

2023-08-29 12:59 UTC, m-orlova commented on content/modules/email-template/pages/usage.adoc
> +  *  *_Code_* -- unique template name; it can be used to find the correct template using API
means "unique template code" intead of "unique template name"?

2023-08-29 13:09 UTC, andreysubbotin commented on content/modules/email-template/pages/index.adoc
> +The add-on enables creating and configuring outbound email templates containing a constant body and variable parameters. A template is created in the visual HTML designer or by using reports. The add
Думаю так же что стоит здесь 2 предложения на одно предложение вида:  The add-on provides a visual HTML editor with an extensive set of HTML elements for creating email templates.

2023-08-29 13:46 UTC, m-orlova reviewed
Review of the "Creation and Last modified" article

2023-08-29 13:46 UTC, m-orlova commented on content/modules/email-template/pages/creation-and-last-modified.adoc
> += Creation and Last Modified
Let's name "JPA Auditing" instead of "Creation And Last Modified"

2023-08-29 13:46 UTC, m-orlova commented on content/modules/email-template/pages/creation-and-last-modified.adoc
> +The screen of the Email Templates UI that allows you to create and edit a template contains a *_Creation and last modified_* section in its left bottom corner, which is supposewd to display the time
1. Replace "screen" with component"
2. Typo in "supposewd"
3. the time -> the date and time

2023-08-29 14:14 UTC, m-orlova reviewed
Additional changes for the "Getting started" article

2023-08-29 14:14 UTC, m-orlova commented on content/modules/email-template/pages/getting-started.adoc
> +Create repositories, Spring for GraphQL controllers and simple CRUD screens for the `Applicant` and `Grant` entities.
**Upd:** We don't use the"screen" term in Amplicode. Let's change "Create simple CRUD screens in the React UI module." to "Create Frontend components for CRUD operations in the React UI module".

2023-08-29 14:14 UTC, m-orlova commented on content/modules/email-template/pages/getting-started.adoc
> +== Creating Data Model and Screens
As we don't use the "screen" term in Amplicode, let's change "Creating Data Model and Screens" to "Creating Data Model and UI".

2023-08-29 14:14 UTC, m-orlova commented on content/modules/email-template/pages/getting-started.adoc
> +After that, the *_Create Email template_* screen is opened. Modify the fields:
Replace "screen" with "component"

2023-09-04 09:28 UTC, m-orlova reviewed
Review part#2.

2023-09-04 09:28 UTC, m-orlova commented on content/modules/email-template/pages/email-scheduler.adoc
> +All existing tasks are listed on the main page of the *_Email Scheduler_* component. By default, all tasks are activated and have an *_Active_* state.
All existing tasks are listed on the main page of the *_Email Scheduler_* component that can be opened from the menu.

2023-09-07 11:44 UTC, andreysubbotin commented on content/modules/email-template/pages/api.adoc
> +Studio offers you special *_Code Snippets_* functionality allowing you to generate standard code snippets for Spring Email operations. These code snippets can be edited later to match your specific n
"to generate standard code snippets for sending email operations"
у нас снипеты больше по api аддона, кажется что Spring Email operations может спутать с использованием стандартного API Spring Mail.

2023-09-07 11:44 UTC, andreysubbotin commented on content/modules/email-template/pages/api.adoc
> +If storing the sent email in History is not required, you can use `JavaMailSender` to send an email.
вот это немного смущает предложение.. у нас же есть еще группа сниппетов по использованию Spring Mail. Как будто это предложение наводит на мысль что нужно еще и их описать и на них ссылаться. Кажется что или убрать это предложение пока что или дописать про снипеты по spring mail.

2023-09-07 12:08 UTC, irinaponomarevahaulmont commented
Ready for a review by Alex B.

2023-09-12 13:27 UTC, alexbudarov requested changes

2023-09-12 13:27 UTC, alexbudarov commented on content/modules/email-template/pages/api.adoc
> +. `Optional<EmailTemplate> findTemplateById(UUID id)` returns an `Optional`  type object with a template found by the specified id, or a `null` if no template is found.
> , or a `null` if no template is found.

should reformulate 
because when method returns Optional, it cannot return null.
I suggest:

> with a template found by specified id/code, if found

Here and 4th item below.

2023-09-12 13:27 UTC, alexbudarov commented on content/modules/email-template/pages/api.adoc
> +. void deleteTemplateByCode(String code) deletes the template with the specified code.
no proper code formatting

2023-09-12 13:27 UTC, alexbudarov commented on content/modules/email-template/pages/api.adoc
> +`EmailTemplate save(EmailTemplate emailTemplate)` saves the specified template.
need to precise: saves new template, and/or saves changes to the existing template

2023-09-12 13:27 UTC, alexbudarov commented on content/modules/email-template/pages/api.adoc
> +If storing the sent email in History is not required, you can use `JavaMailSender` to send an email.
- remove "If storing the sent email ... " sentences from all snippets
- Shortly mention another group of snippets
(e.g. write a TIP: there is also another group of snippets that allow you to send emails by directly using Spring Mail API).

2023-09-18 05:33 UTC, irinaponomarevahaulmont commented on content/modules/email-template/pages/email-history.adoc
> +* Sending
"Not sent" probably doesn't sound very cool, but it describes the situation accurately. I don't know what to replace it with. "Unsent", for example, looks less accurate and can raise questions. So I would let it be.

2023-09-22 09:52 UTC, alexbudarov commented on content/modules/email-template/pages/getting-started.adoc
> +== Adding Source Code
change title to:
> Implement Email Sending Logic

(developers don't say this: "Adding Source Code for ...")

2023-09-25 06:25 UTC, irinaponomarevahaulmont commented
Please review

2023-09-25 14:14 UTC, alexbudarov requested changes
few cosmetics

2023-09-25 14:14 UTC, alexbudarov commented on content/modules/email-template/pages/email-history.adoc
> +* *Not sent* (the emails that hasn't been sent either because it is scheduled to be sent later or because sending has failed for some reason).
> emails
> hasn't

2023-09-25 14:14 UTC, alexbudarov commented on content/modules/email-template/pages/email-history.adoc
> +* *Not sent* (the emails that hasn't been sent either because it is scheduled to be sent later or because sending has failed for some reason).
> the emails that hasn't been sent either because it is scheduled to be sent later

I believe, this is incorrect. Such emails are "Sending".
Consult with Maria pls.

2023-09-25 14:14 UTC, alexbudarov commented on content/modules/email-template/pages/api.adoc
> +. `params` –- a map that contains values for input parameters of the email template. In the map: `key` is an input parameter alias, and `value` is an input parameter value that should be set in the e
>  –-

bad dash

2023-09-28 07:21 UTC, alexbudarov commented on content/modules/email-template/pages/api.adoc
> +    .build(); <7>
Not done.

@m-orlova

Let's introduce a variable for the created email template. Example:

String templateContent = "Hi, ${customerName}. Your subscription has been created. " +
        "Expiry date: ${expiryDate}."; <1>
EmailTemplate template = EmailTemplateBuilder.of("New subscription", "new_subscription", templateContent) <2>
    .addRequiredParameter("Customer name", "customerName", ParameterType.STRING) <3>
    .addRequiredParameter("Subscription expiry date", "expiryDate", ParameterType.DATE) <4>
    .withSubject("New subscription") <5>
    .withFrom("from@company.com") <6>
    .build(); <7>

2023-09-29 15:52 UTC, merged