The first draft of the Bulk Generator section #33
Amplicode/amplicode-docs pull request #36
Opened 2023-09-07 09:49 UTC by irinaponomarevahaulmont

Please review the first draft.

2023-09-08 14:11 UTC, alexbudarov requested changes

2023-09-08 14:11 UTC, alexbudarov commented on content/modules/studio/pages/creating-graphql-controllers.adoc
> +For simplicity, this dialog window contains a reduced number of parameters in comparison with the dialog used to create one controller at a time. For example, it offers filtering by local attributes
GraphQL Controllers by Repository
-->
GraphQL Controller by Repository

2023-09-08 14:11 UTC, alexbudarov commented on content/modules/studio/pages/creating-graphql-controllers.adoc
> +If you need more detailed configuration that specifies which attributes can be used for sorting and filtering or makes use of pagination options, use the dialog available under *_Spring for GraphQL_*
GraphQL Controllers by Repository
-->
GraphQL Controller by Repository

2023-09-08 14:11 UTC, alexbudarov commented on content/modules/studio/pages/creating-graphql-controllers.adoc
> +The load list capabilities group allows us to configure the functionality offered by the list load operation, as we have already xref:#capabilities[mentioned above]:
> load list capabilities

Style as caption text

2023-09-08 14:13 UTC, alexbudarov requested changes

2023-09-08 14:13 UTC, alexbudarov commented on content/modules/studio/pages/creating-graphql-controllers.adoc
> +The repository table displays for you the list of all repositories, for which there are no controllers created.
> all repositories

all Spring Data repositories

2023-09-08 14:23 UTC, alexbudarov commented
You need to restructure the content a little bit. Not just record what I say in a call. This is your role - to think how to structure the content so it doesn't contain duplications, contains information in a best form to be understood by the reader.

For example, similar information about the same thing - "Load list capabilities" is written twice:

1) 

> You can also check or uncheck ... , as well as the load list capabilities. For example, if you don’t need Filtering and Sorting to be supported on your controllers, and only intend to use Pagination, you set the checkboxes as follows:
 << screenshot >>
In this case, the resulting souce code of the controller will only contain the methods needed for Pagination.

2) Second time - below.

> The load list capabilities group allows us to configure the functionality offered by the list load operation, as we have already mentioned above:
  Filtering by local attributes
  Pagination
  Sorting by local attributes
 << very similar screenshot >>
 If you need more detailed configuration that specifies which attributes can be used for sorting and filtering or makes use of pagination options, use the dialog available under Spring for GraphQL → GraphQL Controllers by Repository to create controllers individually. 

The same about table of repositories - they are described twice, a bit differently.
What happens after clicking OK - also described twice.

2023-09-13 09:50 UTC, irinaponomarevahaulmont commented
Please review the changes.

2023-09-17 13:17 UTC, alexbudarov requested changes

2023-09-17 13:17 UTC, alexbudarov commented on content/modules/studio/pages/creating-graphql-controllers.adoc
> +The *_load list capabilities_* group allows us to configure the functionality offered by the list load operation:
load  --> Load

2023-09-19 15:46 UTC, merged