The first draft for user-defined scalar types #34
Amplicode/amplicode-docs pull request #37
Opened 2023-09-13 05:11 UTC by irinaponomarevahaulmont

Please review the first draft.

2023-09-17 14:25 UTC, alexbudarov requested changes

2023-09-17 14:25 UTC, alexbudarov commented on content/modules/studio/pages/user-defined-scalar-types.adoc
> +We have created a query that takes a system locale as an argument and returns the same system locale. It converts a `Locale` object into `String` and back.
> We have created a query that takes a system locale as an argument and returns the same system locale.

It's not an achievement... It wasn't intended by user. It's just a pretty lazy example. Creating a query that takes locale and returns locale wasn't the purpose of the chapter.

Instead, for example:
This is how we can register a custom scalar type in the project and implement its conversion methods.

2023-09-17 14:25 UTC, alexbudarov commented on content/modules/studio/pages/user-defined-scalar-types.adoc
> +It is much harder to parse such an object to GraphQL, since it will be necessary to pass each field separately. The concept of scalars has been introduced to simplify the procedure of passing complic
> It is much harder to parse such an object to GraphQL, since it will be necessary to pass each field separately.

not very good explanation from a developer's perspective.
Instead:
> As you can see, such simple type as `Locale` which is best represented by a simple string code, without a registered scalar type becomes a mess.

2023-09-17 14:25 UTC, alexbudarov commented on content/modules/studio/pages/user-defined-scalar-types.adoc
> +It is much harder to parse such an object to GraphQL, since it will be necessary to pass each field separately. The concept of scalars has been introduced to simplify the procedure of passing complic
passing complicated Java objects as basic types (strings or numbers) to GraphQL
-->
converting complex Java objects to compact GraphQL format

2023-09-17 14:25 UTC, alexbudarov commented on content/modules/studio/pages/user-defined-scalar-types.adoc
> +When we choose the *_Existing scalar type_* option, the *_Scalar type_* drop-down box displays the list of types from the https://github.com/graphql-java/graphql-java-extended-scalars[Extended Scalar
> list of types from

add an adjective somewhere:

> already implemented

2023-09-17 14:25 UTC, alexbudarov commented on content/modules/studio/pages/user-defined-scalar-types.adoc
> +As you can see, both the query and the type itself are marked as *_new_*, which means that the necessary adjustments will be made for them.
You are not making accent on the main thing.
If you click on the return type node, you will see that Studio correctly suggests java.util.Locale class in Java for the Locale type name from GraphQL.

2023-09-17 14:25 UTC, alexbudarov commented on content/modules/studio/pages/user-defined-scalar-types.adoc
> +
Both examples: existing scalar type and new scalar type - lack testing.
You can't be sure that this code is working if you haven't tested it somehow.

In Amplicode we can test the code either via the React UI, or with some GraphQL client (e.g. Altair).
For this chapter - Altair is simpler.

So I suggest you to demonstrate how user can test their scalar type by calling a query from Altair GraphQL client.
Like I did in my demo.
Add steps:
download Altair from this site
restart backend
connect with Altair to our backend
test the query

2023-09-20 07:51 UTC, irinaponomarevahaulmont commented
Please review the changes.

2023-09-29 16:19 UTC, alexbudarov requested changes

2023-09-29 16:19 UTC, alexbudarov commented on content/modules/studio/pages/user-defined-scalar-types.adoc
> +This query, when run, will return your system locale as `en-EN`, `fr-FR`, `de-DE`, etc... In order to see it, we can perform a simple test described below.
"en-EN" locale does not exist, it is invalid.
https://stackoverflow.com/questions/31650521/is-en-en-a-valid-language-locale


Please replace it with en-US or en-GB in the text and screenshots.

2023-09-29 16:19 UTC, alexbudarov commented on content/modules/studio/pages/user-defined-scalar-types.adoc
> +By default, Amplicode uses a predefined set of types for GraphQL. It also allows you to add custom (user-defined) scalar types.
Add inline link here to /studio/scalar-types.html#scalar-types section, where these predefined types are listed.

2023-09-29 16:19 UTC, alexbudarov commented on content/modules/studio/pages/user-defined-scalar-types.adoc
> +The *_Scalar Type Editor_* also allows us to add new types and remove them. For example, to remove a type, put your cursor on it, click the *_Minus_* button and then click *_OK_*. The type will disap
> Scalar Type Editor

Such caption doesn't exist. The dialog is named differently. Here and below.

2023-09-29 16:19 UTC, alexbudarov commented on content/modules/studio/pages/user-defined-scalar-types.adoc
> +Altair supports the following HTTP methods: POST, GET, PUT and DELETE, but POST is the default value. Leave it as it is.
> Altair supports the following HTTP methods: POST, GET, PUT and DELETE

This information is irrelevant for our purpose. Just say that user should keep POST as HTTP method.

2023-09-29 16:19 UTC, alexbudarov commented on content/modules/studio/pages/user-defined-scalar-types.adoc
> +If we add another query manually to the schema in our demo application, it will be highlighted in yellow to show that it doesn't have a controller method.
> doesn't have a controller method

I would add: corresponding

2023-10-02 12:16 UTC, irinaponomarevahaulmont commented
Please review.

2023-10-06 07:46 UTC, merged