Addons to vscode branch
Amplicode/amplicode-docs pull request #46
Opened 2023-10-23 06:46 UTC by irinaponomarevahaulmont

Please review.

2023-10-27 09:25 UTC, alexbudarov requested changes

2023-10-27 09:25 UTC, alexbudarov commented on content/modules/vscode-extension/pages/addon-installation.adoc
> +For the purpose of this article we assume that the backend is being developed in IntelliJ IDEA Community edition, and the frontend in VS Code.
the backend --> the application backend

clarify a bit

2023-10-27 09:25 UTC, alexbudarov commented on content/modules/vscode-extension/images/addons/package-json-added-dependencies.png
it seems here that we added two dependencies (should be only one - addon-email-templates)

2023-10-30 06:21 UTC, irinaponomarevahaulmont commented
Please review

2023-10-31 08:05 UTC, merged