Vscode react components branch
Amplicode/amplicode-docs pull request #47
Opened 2023-10-23 06:52 UTC by irinaponomarevahaulmont

Please review.

2023-10-27 09:44 UTC, alexbudarov requested changes

2023-10-27 09:44 UTC, alexbudarov commented on content/modules/vscode-extension/pages/react-component-wizard.adoc
> +The *_Blank Component_* template allows us to create a blank component and register it in the application’s menu and in the routing configuration. Use this option is you need to create a page that do
is you need --> if you need

2023-10-27 09:44 UTC, alexbudarov commented on content/modules/vscode-extension/pages/react-component-wizard.adoc
> +On the Step 1 the only parameter is *_Query to load items_*, which allows us to select the query tha will be used to load the list of items for the component.
tha -> that

2023-10-27 09:44 UTC, alexbudarov commented on content/modules/vscode-extension/pages/react-component-wizard.adoc
> +Once the wizard's work is completed, the extension modifies the React client file and opens the generated component in the code editor.
if we speak about one file - then should be: extension creates ...
if we speak about several files (one that is being created, and other configuration files that are modified)
then should be: extension modifies React client files ...

2023-10-27 09:44 UTC, alexbudarov commented on content/modules/vscode-extension/images/wizard/vscode-created-file.png
please retake this screenshot after you invoke "npm run generate", so the red highlighting of the imports goes away.

2023-10-30 09:13 UTC, irinaponomarevahaulmont commented
Please review the changes.

2023-10-31 08:09 UTC, alexbudarov commented
solve merge conflict pls

2023-11-16 04:24 UTC, irinaponomarevahaulmont commented
Resolved, please merge.

2023-11-16 10:31 UTC, merged