GraphQL client generation wizard first draft #49
Amplicode/amplicode-docs pull request #51
Opened 2023-10-30 06:08 UTC by irinaponomarevahaulmont

Please review

2023-11-10 11:51 UTC, alexbudarov requested changes

2023-11-10 11:51 UTC, alexbudarov commented on content/modules/studio/pages/external-graphql-apis.adoc
> +Modern web applications work with various data sources. These data sources are not limited by the relational database category only. They may be integrated with other web applications, meaning that t
> They may be integrated

they - who? data sources? ambigious

2023-11-10 11:51 UTC, alexbudarov commented on content/modules/studio/pages/external-graphql-apis.adoc
> +
where is description of other fields? at least service name.

2023-11-10 11:51 UTC, alexbudarov commented on content/modules/studio/pages/external-graphql-apis.adoc
> +When you click `Create`, the https://github.com/Netflix/dgs-codegen[Maven plugin fom the GraphQL DGS library] starts running to generate the necessary code. The files that will be generated by this p
`external.<projectname>`
-->
`external.<serviceName>`

2023-11-10 11:51 UTC, alexbudarov commented on content/modules/studio/pages/external-graphql-apis.adoc
> +The `external.<projectname>` package contains:
`external.<serviceName>`

2023-11-10 11:51 UTC, alexbudarov commented on content/modules/studio/pages/creating-graphql-controllers.adoc
> +== Support of GraphQL Web Services while Creating Spring for GraphQL Controllers
shorten.

Just "Support of External GraphQL Web Services".
Because we are inside the "Creating GraphQL Controllers"  chapter anyways.

2023-11-10 11:51 UTC, alexbudarov commented on content/modules/studio/pages/creating-graphql-controllers.adoc
> +If we choose the *_Expose method of Spring Bean_* option and specify a xref:studio:external-graphql-apis.adoc[web service] as a *_Delegate bean_*, while using any of the query/mutation creation wizar
web service
-->
web service client

2023-11-10 11:51 UTC, alexbudarov commented on content/modules/studio/pages/creating-graphql-controllers.adoc
> +        if (page != null) {
in this sample - omit unnecessary details - logic of page transformation.

replace with:
```
        // ...
```

2023-11-10 11:52 UTC, alexbudarov requested changes

2023-11-10 11:52 UTC, alexbudarov commented on content/modules/studio/images/graphql-apis/choosing-graphql-schema.png
please blur or clean cyrillic UI elements from this screenshot

2023-11-10 11:52 UTC, alexbudarov commented on content/modules/studio/images/graphql-apis/file-choice-dialog.png
clean out cyrillic UI elements from here

2023-11-20 05:03 UTC, irinaponomarevahaulmont commented
Images cleaned, please review.

2023-11-21 11:55 UTC, irinaponomarevahaulmont commented
Please review.

2023-11-27 08:04 UTC, alexbudarov commented on content/modules/studio/pages/external-graphql-apis.adoc
> +Modern web applications work with various data sources. These data sources are not limited by the relational database category only. They may be integrated with other web applications, meaning that t
> These data sources may be integrated with other web applications

Incorrect.
These applications may be integrated ...

2023-11-27 08:29 UTC, alexbudarov requested changes
+ 1 comment left above

2023-11-27 08:29 UTC, alexbudarov commented on content/modules/studio/pages/external-graphql-apis.adoc
> +Under *_Service name_* we enter the name of our future application. *_Target module_*, *_Target package_* and *_Remote service URL_* are already filled in with their default values, which can be left
> and *_Remote service URL_* are already filled in with their default values, which can be left as they are

Incorrect for URL.
Remember that this page is not a tutorial. Users can follow the same instruction for other web service.

Remote service URL - URL of the remote GraphQL API. Change if required.

2023-11-27 08:29 UTC, alexbudarov commented on content/modules/studio/pages/external-graphql-apis.adoc
> +When you click `Create`, the https://github.com/Netflix/dgs-codegen[Maven plugin fom the GraphQL DGS library] starts running to generate the necessary code. The files that will be generated by this p
fom --> from

2023-11-27 09:59 UTC, irinaponomarevahaulmont commented
Please review.

2023-12-01 07:47 UTC, merged