Vscode themes branch
Amplicode/amplicode-docs pull request #59
Opened 2023-11-28 07:57 UTC by irinaponomarevahaulmont

Please review the original draft

2023-12-01 13:23 UTC, alexbudarov requested changes

2023-12-01 13:23 UTC, alexbudarov commented on content/modules/vscode-extension/pages/vscode-themes.adoc
> +[TIP]
The same tip twice, so near to each other?

2023-12-05 10:13 UTC, irinaponomarevahaulmont commented
Please review the changes

2023-12-06 09:15 UTC, alexbudarov requested changes

2023-12-06 09:15 UTC, alexbudarov commented on content/modules/vscode-extension/pages/vscode-themes.adoc
> +. Users can navigation to the theme definition file to edit it (image:themes/edit.png[]).
can navigate ?

2023-12-06 09:15 UTC, alexbudarov commented on content/modules/vscode-extension/pages/vscode-themes.adoc
> +Once this action is completed, a set of files gets created, which defines the theme. The created theme becomes available for using in the project *and customization*.
I didn't mean to write it in bold. I was just emphasising it in the comment.

2023-12-06 09:35 UTC, irinaponomarevahaulmont commented
Please review second round of changes.

2023-12-07 14:30 UTC, merged