Security OIDC branch
Amplicode/amplicode-docs pull request #62
Opened 2023-12-11 10:06 UTC by irinaponomarevahaulmont

Please review the first draft.

2023-12-15 10:21 UTC, alexbudarov requested changes

2023-12-15 10:21 UTC, alexbudarov commented on content/modules/studio/pages/stateful-oidc-authentication.adoc
> +Choose the *_OAuth 2.0 / OIDC Authentic ation (stateful, works with Facebook, Google, Github, Keycloak and Okta)_* radiobutton and click *_Next_*.
> Authentic ation

typo

2023-12-15 10:21 UTC, alexbudarov commented on content/modules/studio/pages/stateful-oidc-authentication.adoc
> +On the second step we fill in the following parameters:
You forgot Client ID

2023-12-15 10:21 UTC, alexbudarov commented on content/modules/studio/pages/stateful-oidc-authentication.adoc
> +All communications between the application and the Keycloak server is done via backend.
..., so we don't need to specify any Keycloak connection settings for the frontend.

2023-12-15 10:21 UTC, alexbudarov commented on content/modules/studio/pages/stateful-oidc-authentication.adoc
> + Шеы `"roles"` parameter must match the xref:#token-claim-name[*_Token Claim Name_*] parameter, which we have set in Keycloak while setting up the *_Client scope_*.
> Шеы

typo

2023-12-15 10:21 UTC, alexbudarov commented on content/modules/studio/pages/stateful-oidc-authentication.adoc
> + Шеы `"roles"` parameter must match the xref:#token-claim-name[*_Token Claim Name_*] parameter, which we have set in Keycloak while setting up the *_Client scope_*.
bad formatting of this paragraph

2023-12-15 10:21 UTC, alexbudarov commented on content/modules/studio/pages/stateful-oidc-authentication.adoc
> +This ensures automatica addition of the prefix to all role names.
> automatica

typo

2023-12-15 10:21 UTC, alexbudarov commented on content/modules/studio/pages/stateful-oidc-authentication.adoc
> +*_Valid redirect URIs_* should contain the mask for the URI where our web client is to be run, e.g. `http://localhost:3000/*`. This value defines, which application will be allowed to use the Keycloa
bad formatting of the remaining paragraph after "http://localhost:3000/*"

2023-12-19 08:04 UTC, irinaponomarevahaulmont commented
Requested changes applied, please review.

2023-12-22 12:26 UTC, alexbudarov requested changes

2023-12-22 12:26 UTC, alexbudarov commented on content/modules/studio/pages/stateful-oidc-authentication.adoc
> +When this type of authentication is set up, all information about the users, including their logins, passwords, other attributes and assigned roles are stored in a separately deployed Keycloak server
Bad formatting for the link

2023-12-22 12:26 UTC, alexbudarov commented on content/modules/studio/pages/stateful-oidc-authentication.adoc
> +Choose the *_OAuth 2.0 / OIDC Authentic ation (stateful, works with Facebook, Google, Github, Keycloak and Okta)_* radiobutton and click *_Next_*.
> Authentic action 

OMG

Authentication!

2023-12-22 12:26 UTC, alexbudarov commented on content/modules/studio/pages/stateful-oidc-authentication.adoc
> +* *_Client ID_*: `oidcdemo` (the name of the Amplicode-based application)
> the name of the Amplicode-based application


Incorrect. It is the value that we entered previously in KeyCloak.

2023-12-22 12:26 UTC, alexbudarov commented on content/modules/studio/pages/stateful-oidc-authentication.adoc
> +[source]
why no code highlighting in this snippet?

2023-12-25 07:40 UTC, irinaponomarevahaulmont commented
Requested changes applied, please review.

2023-12-27 08:02 UTC, merged