Security ldap branch
Amplicode/amplicode-docs pull request #66
Opened 2023-12-25 04:14 UTC by irinaponomarevahaulmont

First draft ready, please review.

2023-12-27 09:06 UTC, alexbudarov requested changes

2023-12-27 09:06 UTC, alexbudarov commented on content/modules/studio/pages/ldap.adoc
> +*_Group search base_* should be `ou=groups`.
add explanation:

> Base directory to search for authorities. The application will search for groups of which the user is a member (typically these will be groupOfNames or groupOfUniqueNames entries in the directory). Roles will be assigned to the user by searching under the "Group search base" with the default filter (member=<user's-DN>). The role name will be taken from the “ou” attribute of each match. 

(took from https://docs.spring.io/spring-security/site/docs/3.1.x/reference/ldap.html)

2023-12-27 09:06 UTC, alexbudarov commented on content/modules/studio/pages/ldap.adoc
> +=== Checking Connection Parameters.
remove dot in the end

2024-01-04 06:54 UTC, irinaponomarevahaulmont commented on content/modules/studio/pages/ldap.adoc
> +With the modifications we have made, if the current user is an LDAP user (`InetOrgPerson`) and it has the `cn` field filled in, we retrieve its value and use it as the user's full name.
No, because LDAP sounds "el-di-ei-pi" when pronounced.

2024-01-06 07:25 UTC, irinaponomarevahaulmont commented
Please review the first round of requested changes.

2024-01-10 14:55 UTC, alexbudarov commented on content/modules/studio/pages/ldap.adoc
> += Security -- Using LDAP with Amplicode-based Projects
not fixed

2024-01-11 04:18 UTC, irinaponomarevahaulmont commented on content/modules/studio/pages/ldap.adoc
> += Security -- Using LDAP with Amplicode-based Projects
OK, guess I misunderstood you.

2024-01-11 04:19 UTC, irinaponomarevahaulmont commented
Please review.

2024-01-11 11:56 UTC, merged