Bean validation branch
Amplicode/amplicode-docs pull request #67
Opened 2024-01-06 09:41 UTC by irinaponomarevahaulmont

Please review the original draft.

2024-01-11 14:51 UTC, alexbudarov requested changes

2024-01-11 14:51 UTC, alexbudarov commented on content/modules/studio/pages/bean-validation.adoc
> +In React UI the *_Create_* and *_Edit_* screens contain built-in processing functionality for the Been Validation errors that come from the server.
Been  --> Bean

2024-01-11 14:51 UTC, alexbudarov commented on content/modules/studio/pages/bean-validation.adoc
> +The dialog window for specifying the localized message will appear. Now we enter `Price must be positive` under *_Default_* and `Il prezzo deve essere positivo` under *_Italian_*.
Paragraphs order is messed a bit.
As I understand, this should follow directly after the "then click on the Intention (the bulb icon) and select Create or edit localized message"

2024-01-11 14:51 UTC, alexbudarov commented on content/modules/studio/pages/bean-validation.adoc
> +image::bean-validation/validation-messages.png[align=center]
screenshot is too big. Cut or scale.

2024-01-11 14:51 UTC, alexbudarov commented on content/modules/studio/pages/bean-validation.adoc
> +image::bean-validation/project-tool-window.png[align=center, width=450]
screenshot is too big. Cut or scale.

2024-01-12 05:26 UTC, irinaponomarevahaulmont commented
Please review the changes

2024-01-12 10:22 UTC, merged