VS Code Preview first draft #68
Amplicode/amplicode-docs pull request #74
Opened 2024-01-17 06:56 UTC by irinaponomarevahaulmont

Please review the first draft.

2024-01-18 13:11 UTC, alexbudarov requested changes

2024-01-18 13:11 UTC, alexbudarov commented on content/modules/vscode-extension/pages/vscode-preview.adoc
> +The file used in this example, `ToggleThemeButton.txs`, is located under `src` -> `app` -> `app-bar` and is present in any frontend project generated with the help of the Amplicode extension. It is r
.txs --> .tsx

2024-01-18 13:11 UTC, alexbudarov commented on content/modules/vscode-extension/pages/vscode-preview.adoc
> +The component in the preview mode is interactive and toggles. If you click on it, its look will change in just the same way as it does when the complete frontend is opened in the browser.
> and toggles

strange. you can delete it, you've described the behavior in th next sentence.

2024-01-19 11:21 UTC, irinaponomarevahaulmont commented
Please review the changes

2024-01-22 09:34 UTC, alexbudarov requested changes

2024-01-22 09:34 UTC, alexbudarov commented on content/modules/vscode-extension/pages/vscode-preview.adoc
> += VS Code Preview
VS Code Preview --> Preview

2024-01-22 09:38 UTC, irinaponomarevahaulmont commented
Please review the second round.

2024-01-22 14:44 UTC, merged