Tutorial branch
Amplicode/amplicode-docs pull request #8
Opened 2023-05-02 08:08 UTC by irinaponomarevahaulmont

Please check the first draft.

2023-05-06 11:06 UTC, alexbudarov requested changes
Will also discuss main points during the next sync call.

2023-05-06 11:06 UTC, alexbudarov commented on content/modules/tutorial/pages/customization.adoc
> +        appointmentRepository.save(appointment);
(3)
Save updated Appointment instance

2023-05-06 11:06 UTC, alexbudarov commented on content/modules/tutorial/pages/customization.adoc
> +Implementation of the business logic is completed.
After that I think we should add a tip - reminder.
Don't forget to restart the application backend, to make the changes in the code to be applied to the locally running application.

2023-05-06 11:06 UTC, alexbudarov commented on content/modules/tutorial/pages/project-setup.adoc
I like in Jmix tutorial that in the end of every part there is a Summary section that repeats one more time, what we have learnt to do.
Let's make similar sections in our tutorial.

2023-05-15 09:34 UTC, irinaponomarevahaulmont commented
Please see the latest commits. I have made all the requested corrections.

2023-05-16 15:06 UTC, alexbudarov commented on content/modules/tutorial/pages/repository-creation.adoc
> +If the application doesn't contain any error, it will run successfully.
You have copied my message from the console.
It's not from the tutorial project (other project name).
Please take message from your tutorial project.

2023-05-16 15:32 UTC, alexbudarov commented on content/modules/tutorial/pages/customization.adoc
> +Right-click *_Autowire_* -> *_Data Access/Repositories_*.
You haven't changed here. But the phrase is incomplete, there is no instruction to choose an item in the context menu.

2023-05-16 15:34 UTC, alexbudarov commented on content/modules/tutorial/pages/customization.adoc
> +Switch to the **__AppointmentRequestResult.java __**file and add two constructors to the *_AppointmentRequestResult_* class, one without arguments and the other one taking *_"reserved"_* (a boolean v
Typo in the new text (theGenerate popup menu). And no highlighting of the Generate. And no shortcut for MacOS.

2023-05-16 15:50 UTC, alexbudarov commented on content/modules/tutorial/images/transactional.png
again, it's not what should be.
When you enabling @Transactional, the METHOD should be selected in the Inspector, not class. And annotation should be put on the method.

2023-05-17 09:55 UTC, alexbudarov requested changes

2023-05-17 09:55 UTC, alexbudarov commented on content/modules/tutorial/pages/repository-creation.adoc
> +Now we can create the API for our backend application. Studio uses *_Spring GraphQL controllers_* as API. Studio allows us to create a controller via a wizard; the controller will be covering all sim
Studio uses *_Spring GraphQL controllers_* as API.

Here - Amplicode, not Studio (Amplicode as a platform).

2023-05-17 09:55 UTC, alexbudarov commented on content/modules/tutorial/pages/repository-creation.adoc
> +Now we can create the API for our backend application. Studio uses *_Spring GraphQL controllers_* as API. Studio allows us to create a controller via a wizard; the controller will be covering all sim
simple  --> basic
(they are not very simple)

2023-05-17 09:55 UTC, alexbudarov commented on content/modules/tutorial/pages/repository-creation.adoc
> +Expand the collapsible blocks at the bottom of the form. In *_Pagination And Sorting_* check the *_"Pagination"_* checkbox and add `firstName` and `lastName` in *_Fields for sorting_*.
double quotes

2023-05-17 09:55 UTC, alexbudarov commented on content/modules/tutorial/pages/repository-creation.adoc
> +* Studio offers wizards for creating CRUD controllers.
... which represent the external API of the application backend.

2023-05-17 09:55 UTC, alexbudarov commented on content/modules/tutorial/pages/repository-creation.adoc
> +* After creating repositories and controllers it is necessary to regenerate the GraphQL schema, for which Studio provides a quick solution.
"quick solution" isn't the best term for a part of the tooling.
an automated action, I think.

because we automate a process that was intented to be manual (by authors of Spring GraphQL).

2023-05-17 09:55 UTC, alexbudarov commented on content/modules/tutorial/pages/customization.adoc
> +We are reminding you that you can open the *_schema.graphqls_* file either from the Structure tree or from the IDE's own project tree if you would like to see its code.
"We are reminding you that" - looks like a bit of a passive aggression for me.

2023-05-17 09:55 UTC, alexbudarov commented on content/modules/tutorial/pages/customization.adoc
> +Using the Designer panel mark the new method as *_Transactional_*.
Is a "panel mark" a noun?
Comma would help to avoid a confusion.

2023-05-17 09:55 UTC, alexbudarov commented on content/modules/tutorial/pages/customization.adoc
> +Switch to the `AppointmentRequestResult` class and add two constructors to it, one without arguments and the other one taking *_reserved_* (a boolean variable) as an argument. You can use theGenerate
reserved - should be highlighted as code, not as UI caption.

2023-05-17 09:55 UTC, alexbudarov commented on content/modules/tutorial/pages/customization.adoc
> +Press *_Alt+Enter_* (or *_Opt+Enter_* on a Mac) on `CreateNewAppointment` and create the method. The method should have the following code:
CreateNewAppointment --> createNewAppointment

2023-05-17 09:55 UTC, alexbudarov commented on content/modules/tutorial/pages/customization.adoc
> +As we can see from the code, this method fills in all attributes of the `Appointment` entity with their respective values and saves the repository.
saves the repository
?
saves using the repository, or via the repository

2023-05-17 09:55 UTC, alexbudarov commented on content/modules/tutorial/pages/customization.adoc
> +Repeat exactly the same procedure for `Patient` (Name the method: `CountConflictsByPatientAndPeriod`).
method names in Java always start from lowercase letter

2023-05-17 09:55 UTC, alexbudarov commented on content/modules/tutorial/pages/customization.adoc
> +Enable _*Transactional*_ in the Designer, then write up the following code:
Transactional - is badly highlighted in text.
Also, you have not shown the annotation in the code snippet (it should be above the method definition).

2023-05-17 09:55 UTC, alexbudarov commented on content/modules/tutorial/pages/customization.adoc
> +In this section, you have created the customized business logic reflecting the peculiarities of the JPA entities included in the project.
"reflecting the peculiarities of the JPA entities "
don't like it.

JPA entites are not the source of what we do. They are instruments.
The source is - business/functional requirements.

2023-05-17 09:55 UTC, alexbudarov commented on content/modules/tutorial/pages/customization.adoc
> +* Studio supports different approaches to programming: from backend to the schema or vice versa.
approaches to programming
-->
approaches to developing the API layer of the application

2023-05-17 09:57 UTC, alexbudarov commented on content/modules/tutorial/pages/customization.adoc
> +Using the _*bulb*_ pictogram (image:bulb.png[align=center]) activate the adjustment screen for this method. Check the *_id_* checkbox, change the type to `Long` and click *_OK_*.
bulb - bad formatting.

2023-05-17 11:34 UTC, irinaponomarevahaulmont commented on content/modules/tutorial/pages/customization.adoc
> +Right-click *_Autowire_* -> *_Data Access/Repositories_*.
I changed it elsewhere. You asked to mention these opportunities in the Tutorial, but didn't insist that it should be right here. I'll see how to make it complete.

2023-05-18 06:17 UTC, irinaponomarevahaulmont commented
Please check the latest commit.

2023-05-19 15:50 UTC, merged